import { type Metadata } from 'next'
import './globals.css'
import Root from '@/components/root'
import ClerkProviderWrapper from '@/wrapper/clerk/clerk-provider-wrapper'

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProviderWrapper>
      <html lang="en">
        <body className={`antialiased`}>
          <Root>{children}</Root>
        </body>
      </html>
    </ClerkProviderWrapper>
  )
}